#!/bin/bash

source "${WORKSPACE}/profile/.shell-completion.${SHELLNAME}"
source "${WORKSPACE}/profile/.env"
source "${WORKSPACE}/profile/.alias"
source "${WORKSPACE}/profile/.aws"
source "${WORKSPACE}/profile/.brew"
source "${WORKSPACE}/profile/.func"
source "${WORKSPACE}/profile/.gitx"
source "${WORKSPACE}/profile/.hooks"
source "${WORKSPACE}/profile/.msplit"
source "${WORKSPACE}/profile/.shims"
source "${WORKSPACE}/profile/.gox"
source "${WORKSPACE}/profile/.ssl"
source "${WORKSPACE}/profile/.vm"
